import 'package:futbal_gundem/API_Request/Haber_Api.dart';

import 'package:http/http.dart' as http;
import 'dart:convert';
import 'dart:async';

class FanatikService {
  final String postsURL = "http://192.168.1.105/FutbolGundem/fanatik_spor.php";

  Future<List<HaberAPI>> getPosts() async {
    final res = await http.get(postsURL);

    if (res.statusCode == 200) {
      List<dynamic> body = jsonDecode(res.body);

      List<HaberAPI> fanatik_veri = [];

      body.forEach((element) {
        fanatik_veri.add(HaberAPI.fromJson(element));
      });
/*
      List<Autogenerated> posts = body
          .map(
            (dynamic item) => Autogenerated.fromJson(item),
          )
          .toList();
          */

      return fanatik_veri;
    } else {
      throw "Unable to retrieve posts.";
    }
  }
}
